services:

  app:
    build: .
    restart: always
    env_file:
      - .env
    networks:
      default:
      proxy:
networks:
    default:
    proxy:
      external:
        name: nginx-proxy_default
